version: 2

sphinx:
  configuration: docs/conf.py
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.8"
  apt_packages:
    - cmake
    - g++

python:
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
  system_packages: true
