[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "chrysalis"
version = "1.0b"
authors = [
  {name="Demeter Turos"},
]
description = "Lightweight package to create high-quality visualizations of spatial transcriptomics datasets based on spatially variable genes."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/rockdeme/chrysalis"
